name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Standardmäßig Befehle im "barcode-app"-Ordner ausführen
    defaults:
      run:
        working-directory: ./barcode-app

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Build Web Assets
        run: npm run build
        
      - name: Sync Capacitor
        run: npx cap sync
        
      - name: Build Android APK
        run: ./gradlew build
        working-directory: ./barcode-app/android
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          # Pfad zur fertigen APK
          path: barcode-app/android/app/build/outputs/apk/debug/app-debug.apk